FROM docker.io/elixir:1.17-alpine as build

RUN mkdir -p /app/source
WORKDIR /app/source

# install mix deps
COPY mix.exs mix.lock ./
COPY config config

ENV MIX_ENV=prod
RUN mix deps.get --only $MIX_ENV


# build release
COPY lib lib
RUN mkdir /app/release
RUN mix release --path /app/release

# Bundle
WORKDIR /app/release
RUN tar -cavf /release.tar.gz .

